package argonaut

object ArgonautScalaz extends ArgonautScalazs

trait ArgonautScalazs extends
ACursorScalazs with
CodecJsonScalazs with
ContextScalazs with
ContextElementScalazs with
CursorScalazs with
CursorHistoryScalazs with
CursorOpScalazs with
CursorOpElementScalazs with
DecodeJsonScalazs with
DecodeResultScalazs with
EncodeJsonScalazs with
HCursorScalazs with
JsonScalazs with
JsonIdentityScalazs with
JsonObjectScalazs with
PrettyParamsScalazs with
StringWrapScalazs
