package argonaut

object ArgonautMonocle extends ArgonautMonocles

trait ArgonautMonocles extends
ACursorMonocles with
CodecJsonMonocles with
ContextMonocles with
CursorMonocles with
CursorHistoryMonocles with
CursorOpMonocles with
CursorOpElementMonocles with
DecodeJsonMonocles with
DecodeResultMonocles with
EncodeJsonMonocles with
HCursorMonocles with
JsonMonocles with
JsonIdentityMonocles with
JsonObjectMonocles with
PrettyParamsMonocles with
StringWrapMonocles
